screenPositionFP = "BOTTOM_CENTER"
optimalIndicatorFP = true
textColorFP = 16777215
textShadowFP = true
hudDelimiterFP = ""
showYawFP = false
showAltitudeFP = false
showVelocityFP = false
showDirectionFP = false
showDurabilityFP = false
showElytraItemFP = false
screenPositionTP = "MIDDLE_CENTER"
optimalIndicatorTP = true
textColorTP = 16777215
textShadowTP = true
hudDelimiterTP = ""
showYawTP = false
showAltitudeTP = false
showVelocityTP = false
showDirectionTP = false
showDurabilityTP = false
showElytraItemTP = false
ascendAngle = -40
descendAngle = 40
glideAngle = 0
indicatorWidth = 5
durabilityThreshold = 0.05
durabilityPercentage = true
messageColor = 12451840
boldMessage = true
